name: Release

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      deployments: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --tags origin

      - name: 'Build Changelog'
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
            token: '${{ github.token }}'

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: engine_${{ github.sha }}
          body: ${{steps.build_changelog.outputs.changelog}}
          files: |
            Release.txt
